[package]
name = "rust-stream-deck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elgato-streamdeck = "0.5.0"

[dependencies.hidapi]
default-features = false
features = ["linux-static-libusb"]
