[package]
name = "streamdeck"
version = "0.1.0"
edition = "2021"

[lib]
name = "streamdeck"
path = "src/lib.rs"

[[bin]]
name = "debug"
path = "src/bin.rs"

[dependencies]
binrw = "0.12.0"
hidapi = "2.4.1"
pretty-hex = "0.3.0"
thiserror = "1.0.49"
